In [1]:
import numpy as np

# np.array()

In [2]:
arr = np.array([1, 2, 3, 4, 5])
print("np.array():", arr)

np.array(): [1 2 3 4 5]


# np.zeros()

In [3]:
zeros_arr = np.zeros((3, 4))
print("np.zeros():", zeros_arr)

np.zeros(): [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# np.ones()

In [4]:
ones_arr = np.ones((2, 3))
print("np.ones():", ones_arr)

np.ones(): [[1. 1. 1.]
 [1. 1. 1.]]


# np.reshape()

In [5]:
reshaped_arr = np.reshape(arr, (5, 1))
print("np.reshape():", reshaped_arr)

np.reshape(): [[1]
 [2]
 [3]
 [4]
 [5]]


# np.concatenate()

In [6]:
concatenated_arr = np.concatenate((arr, arr))
print("np.concatenate():", concatenated_arr)

np.concatenate(): [1 2 3 4 5 1 2 3 4 5]


# np.mean()

In [7]:
mean_value = np.mean(arr)
print("np.mean():", mean_value)

np.mean(): 3.0


# np.sum()

In [8]:
sum_value = np.sum(arr)
print("np.sum():", sum_value)

np.sum(): 15


# np.min()

In [9]:
min_value = np.min(arr)
print("np.min():", min_value)

np.min(): 1


# np.max()

In [11]:
max_value = np.max(arr)
print("np.max():", max_value)


np.max(): 5


# np.argmax()

In [12]:
argmax_value = np.argmax(arr)
print("np.argmax():", argmax_value)

np.argmax(): 4



# np.argmin()

In [13]:
argmin_value = np.argmin(arr)
print("np.argmin():", argmin_value)

np.argmin(): 0


# np.random.rand()

In [14]:
rand_arr = np.random.rand(3, 3)
print("np.random.rand():", rand_arr)

np.random.rand(): [[0.72279411 0.09127701 0.46133019]
 [0.1991171  0.41078862 0.51150049]
 [0.80770616 0.02863016 0.94105269]]


# np.random.randn()

In [15]:
randn_arr = np.random.randn(2, 2)
print("np.random.randn():", randn_arr)

np.random.randn(): [[ 0.61190514 -0.67088379]
 [ 0.10689752  0.45127617]]


# np.random.randint()

In [16]:
randint_value = np.random.randint(1, 10, size=(2, 2))
print("np.random.randint():", randint_value)

np.random.randint(): [[1 2]
 [5 7]]


# np.dot()

In [17]:
dot_product = np.dot(arr, arr)
print("np.dot():", dot_product)

np.dot(): 55
